### ISSUE TITLE
Introduce task concept

### ISSUE THREAD

**Issue by JanOwiesniak** [JanOwiesniak/duty#2]
It should be possibe to compose easy testable high level tasks such as 'new feature' out of low level commands such as 'checkout branch'.

**Comment by JanOwiesniak** [comment]
https://github.com/JanOwiesniak/duty/pull/18

**Comment by JanOwiesniak** [comment]
Should be closed. Not merged yet. Sorry.

**Comment by JanOwiesniak** [comment]
Anything left on you branch that should be merged into master?
If this is not the case i would close this issue and get rid of the branch.

/cc @rrrene

**Comment by rrrene** [comment]
You could consider keeping https://github.com/JanOwiesniak/duty/commit/f65c480beafa038574fef31bc80d15d3eb38e6fe and https://github.com/JanOwiesniak/duty/commit/0044c772a8ceeac67ef8832838228a8ade1e1422 to get rid of two obvious code smells.

**Comment by JanOwiesniak** [comment]
Done.

**Comment by rrrene** [comment]
:santa: :+1:
