### ISSUE TITLE
Use 'closest' .duty file

### ISSUE THREAD

**Issue by JanOwiesniak** [JanOwiesniak/duty#31]
E.g i'm in `/home/jan/code/project`

`duty` should use `/home/jan/code/project/.duty` if it exists and fallback to `/home/jan/.duty` if not.

**Comment by jnbt** [comment]
Just as a hint: How rubocop is doing it: https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/config_loader.rb#L191-L205

**Comment by rrrene** [comment]
:+1:

Related: is it `.duty` or `.duty.yml` now?

**Comment by jnbt** [comment]
Current state is `.duty.yml`.

**Comment by rrrene** [comment]
Ah, very good (and probably the better choice as it hints at the syntax).

**Comment by JanOwiesniak** [comment]
Thanks! I really appreciate this!
Tested it on my system. Works like a charm!
